version: '3.8'

services:
  app:
    build: .
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb?sslmode=disable
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest

volumes:
  pgdata:
