version: '3.8'

services:
  app:
    build: .
    environment:
      CONFG_PATH: /path/to/config
      GIN_MODE: release
    depends_on:
      - postgres
      - redis
    ports:
      - "8082:8082" # Замените на нужный порт

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
