env: "prod"

storage_path: "user=postgres dbname=dbname password=password host=localhost port=5432 sslmode=disable"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  ttl: 5m

image_settings:
  maxWidth: 5000
  maxHeight: 5000
  chars: "@%#*+=:~-. "

http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s

req_limit:
  max_num_req: 5
  time_slice: 1s
  ban_time: 60s